### ISSUE TITLE
PRE-Nexus Issue tracker (Plus suggestions)

### ISSUE THREAD

**Issue by ingles98** [Persistent-SS13/Persistent-Bay#1122]
I've compiled a bunch of issues/suggestions that were open prior to this Issue's creation.

Thought it would be a good idea since the big Nexus launch is coming up and we will be flooded with new issues to tackle. Trying to keep the page clean.

**KEEP IN MIND SOME OF THESE MIGHT AS WELL BE FIXED ALREADY, UPDATE THIS ACCORDINGLY**

The list, in chronological order. Feel free to re-open any of the issues below.

- [ ] #268 - Server Saving - Saved computers with RFID slots do not keep the remove ID verb
- [ ] #273 - Server Saving - Camera drones create a new camera entry on camera consoles on load
- [x] #307 - General - Turrets shoot at cyborgs regardless of faction/assignment status
- [ ] #477 - Server Saving - Carbon Copy Paper Bug
- [ ] #479 - Server Saving - Cutlet Sandwich Bug
- [ ] #572 - Suggestion - Linkable Shutters/Blast Doors, and more!
- [ ] #573 - Suggestion - Ability to plan rooms via blueprints
- [ ] #576 - Suggestion - ABILITY TO MAKE SIGNS!
- [ ] #577 - General - CREW MANIFEST NULL
- [ ] #578 - General - hemostat
- [x] #580 - General - SCIENCE GOGGLES
- [ ] #582 - General - hidden doors need to be resprited and orientation fixed
- [ ] #588 - Server Saving - Disappearing sprites. (PRODUCE)
- [ ] #599 - Server Saving - pressure regulators not saving properly
- [ ] #600 - General - Seeing the bottom z on top of the top z
- [ ] #601 - Server Saving - normal (not high pressure) pumps not saving properly
- [ ] #602 - Server Saving - filters and mixers disconnecting upon save/load
- [ ] #609 - Server Saving - Floor lights are in a weird limbo state on map load
- [ ] #633 - Server Saving - Saving Issue: Pizza Box's do not save content right.
- [ ] #635 - Suggestion - SUGGESTION: Remove All Access from Cleaning Bots
- [ ] #640 - General - BUG: gas being duped _(Weird bug that has been haunting us for quite some time.)_
- [ ] #668 - General - Weird glitches
- [ ] #671 - General - BUG: LIGHTING ISSUES
- [x] #687 - Server Saving - [Oversight] Newscaster feeds do not save.
- [x] #710 - General - Unathi blood is toxic to Unathi
- [ ] #740 - Server Saving (Probably) - Food loses the recolorable portion of its sprite on cryo or server restart
- [ ] #747 - Server Saving - RCD Matter tank content isn't saved
- [ ] #760 - General - Air alarms, vents and scrubbers behave inconsistently
- [ ] #763 - Server Saving - Some material sheets do not save
- [ ] #775 - General - You can bypass the blueprint room size limit by merging areas together
- [ ] #777 - Server Saving - The solar console resets on reload
- [ ] #779 - General - Coffee is dangerous
- [x] #781 - General - Clocking out of businesses on Lace UI does not work
- [ ] #783 - General - Can't hit, grab, or disarm cleaner bots
- [ ] #784 - General - Microwave cannot be disassembled
- [ ] #785 - General - Cannot disassemble cyogenic freezers
- [ ] #786 - General - Newscasters can't be taken off or disassembled
- [ ] #789 - General - keypad doors accept any airlock electronics circuit
- [ ] #794 - Server Saving (Probably)- Door have no air on reload
- [x] #795 - General - Jetpacks don't work when attached to a suit. _(I tested this myself without knowing about this issue, and it was working. Will leave this unchecked anyways.)_
- [ ] #796 - Suggestion - The_Revanchist's Suggestion list (Forum thread URL)
- [ ] #797 - General - Can't put label on large boxes
- [ ] #798 - General - Light amplifications google in the tactical armor kit don't turn off properly
- [ ] #800 - General - Cryo Tubes Broken
- [ ] #804 - General - Plastic sheets transmute into steel via disassembling sink frame.
- [ ] #806 - General/Server Saving - Cryofrozen cards do not devalidate
- [ ] #807 - General - Shuttle Creation Bugged _(After Nexus this sure will be completely different anyways.)_
- [ ] #809 - General - cleanbots (all simple bots?) can bypass business airlocks
- [x] #812 - Suggestion - Sugestion create a public market.
- [ ] #817 - Server Saving - Cloaks act very strangely as containers (Edit)
- [ ] #819 - Suggestion - suggestion to make transit toobs buildable.
- [x] #821 - Suggestion - Add the possibility to disable export for the business
- [ ] #823 - Server Saving - Manual valve position do not save
- [ ] #824 - Server Saving - UI for valves/valves are disabled on reboot
- [x] #825 - Server Saving - Money in containers can sometimes lose its sprite on reload
- [x] #833 - General - Mateba, Magnum and .50 cal
- [ ] #847 - General - Unintended Floor tiles to steel walls. Girder dupe.
- [ ] #848 - General - holopads don't work
- [ ] #884 - General (Suggestion perhaps) - Can't fill up air tanks using canister
- [ ] #885 - General - radioless airlock controller
- [ ] #886 - General - All languages selectable on character creation.
- [ ] #905 - Suggestion - sugestion I want to add a bulk medical item for roll gauze trauma kits burn kits and ointement
- [x] #912 - Suggestion - Suggestion: adding classical music ;)
- [ ] #913 - General - no radio airlock controllers can bypass keypad airlock bolts on cycle
- [x] #922 - General - Bug fix : autolathe can't be dismantle.
- [ ] #926 - General - (Integrated Circuits) - Hypo-Injector Circuit does not inject mobs
- [ ] #932 - General - Cooking recipes not working correctly
- [ ] #940 - General - Free Air Tanks
- [ ] #946 - General - Jumpsuit Accessory Bug
- [ ] #951 - Server Saving - Blood Packs Disappear from IV Drips on Restart
- [ ] #952 - Server Saving - Medibot Settings Reset to Default After Restart
- [x] #958 - General - Fix Email system
- [ ] #985 - Suggestion List - This new issue is to regroup all sugestion concerning export and import.
- [ ] #988 - Suggestion - Sugestion : Add a new organ "the stomach"
- [ ] #996 - TYPE - Bug: Infinite Chicken Meat!
- [ ] #1001 - General - Species specific emotes are not on the list of usable emotes
- [ ] #1002 - General - Slowing down hydroponics plant harvest by 10 times or more
- [x] #1007 - General - Server crashes after being online for too long
- [ ] #1008 - Server Saving - Oxygen in tank does not save when in a voidsuit and on reload.
- [ ] #1012 - Suggestion - Sugestion make more specialize machine not an autolathe that can make anything.
- [ ] #1018 - Server Saving - Produce turning useless. Server Saving Issue
- [ ] #1037 - Suggestion - Sugestion Total change of the economy adding a bank local money and license for export
- [ ] #1049 - Suggestion - Sugestion please add a template for vending cart.
- [ ] #1059 - Issue List - RIGsuits general issue list
- [ ] #1060- Suggestion - Suggestion: Cleaning stuff
