### ISSUE TITLE
To-Do Buglist

### ISSUE THREAD

**Issue by matt81093** [Persistent-SS13/Persistent-Bay#195]
Ew an out of date buglist.. I need to fix this mess.

Er personal list of bugs
- [x] beaker unable to be inserted into sleeper #198 
- [ ] languages don't work [not working on atm]
- [ ] correct neural lace in clones issue
- [ ] ChemMaster erases excess liquid beaker -> buffer
- [ ] mobs without lower bodies cause client crashing?
- [ ] ore refinement equipment won't smelt/refine with console built
- [ ] HighSec airlock deconstuct gives regular and secure airlock electronics
- [ ] sleepers allow duping, ie extra matter bins when upgraded
- [x] racks-yield-plastic #209 
- [ ] syncing exofab casued 2 minute lag
- [ ] certain system don't load before players log into game, manual initiating needed
- [ ] temperature gun causes crashes
- [ ] floor lights appear on when game loaded, lights need updated though
- [ ] Drag or grab-placing someone onto surgery table occasionally results with insta-failure during surg
- [ ] Rollerbeds occasionally drop patients;  An error should appear in log with /error()
- [ ] meat slab monkeys create 4 meat slabs; cloning req 3
- [x] authlathe prob doesn't accept copper
- [x] autholathe prints cable coil that req copper AND coil that doesn't. (Prints one piece at time?)
- [ ] Co2 canisters changing to N2 canisters
- [ ] RIG jetpacks stop working on server reload [var issue?]
- [ ] solar panels needs reconfigured on reload?
- [ ] knife gibs limbs
- [ ] invoice program nonfunctional, doesn't print invoice
- [ ] organ scarring undetectable
- [ ] gibbing heads destroys laces

Objects that need to be saved
- [ ] laces?
- [ ] Solar trackers
- [ ] Fingerprints
- [ ] floor_lights
- [ ] atmos filters, pumps, etc
- [ ] modified plants
- [ ] signalling and wiring
- [ ] machine uids, counter saving
- [ ] (integrated?) circuit signallers and circuit hypo injectors
- [ ] nav beacons
- [ ] reagents in
   /obj/item/integrated_circuit/manipulation/injector
   /obj/item/integrated_circuit/manipulation/smoke
- [ ] frequency and code in
/obj/item/integrated_circuit/input/signaler
/obj/item/integrated_circuit/input/signaler/advanced

Port goals/ code changes
- [ ] way to force icon updates on objects?
- [ ] drone to deliver materials to station automatically and return to gps? location of user
- [ ] forge like machine, that can utilise multiple enery sources for power and heat (limit to heat?)
- [ ] monkeys have human screams
- [ ] implement integrated circuit blueprint saving
- [ ] buildable defibs
- [ ] sinks (and others) should use timer based on amount being filled
- [ ] allow air canisters to be desconstructed without breaking them
- [ ] walls | tuft -> contu
- [ ] make everything not a \weapon\
- [ ] port over components?
- [ ] port over TG circuits
- [ ] simple bots
stationary option | return to X option

**Comment by Zero-Bits** [comment]
Clones spawning with lace's has been fixed.

**Comment by ingles98** [comment]
Requesting update on these bugs i think most of them have been fixed already

**Comment by Kurgis** [comment]
@ingles98 I'm requesting that this be closed. It's a list of various issues which goes without proper explanation, and its last update was 28 days ago.
